### ISSUE TITLE
the code itself may has big mistake

### ISSUE THREAD

**Issue by goodmanchd** [moveit/py_binding_tools#1]
![image](https://github.com/user-attachments/assets/9d313fde-3f61-439d-b0c0-fa6dfce58f2d)
seriously?

**Comment by goodmanchd** [comment]
so that this is a key component in the moveit tools, and i cant use that because this doesn't work

**Comment by facontidavide** [comment]
Thanks for the constructive criticism. I am sure that the team at Picknik will investigate this with utmost celerity

**Comment by rhaschke** [comment]
The code compiles without issues in CI: https://github.com/moveit/py_binding_tools/actions/runs/10613882842
The `SingleThreadedExecutor` derives from `Executor,` which [provides `spin_all`](https://docs.ros.org/en/rolling/p/rclcpp/generated/classrclcpp_1_1Executor.html#_CPPv4N6rclcpp8Executor8spin_allENSt6chrono11nanosecondsE).
To help with your concrete issue, it would be helpful if you provide some information about your setup:
Which ROS distro are you using?

**Comment by goodmanchd** [comment]
> 代码在 CI 中编译没有问题：https://github.com/moveit/py_binding_tools/actions/runs/10613882842`SingleThreadedExecutor`由此 得出`Executor,`​[提供`spin_all`](https://docs.ros.org/en/rolling/p/rclcpp/generated/classrclcpp_1_1Executor.html#_CPPv4N6rclcpp8Executor8spin_allENSt6chrono11nanosecondsE)。 为了帮助解决您的具体问题，如果您提供一些有关您的设置的信息会很有帮助： 您使用哪个 ROS 发行版？

ros2 roxy, ubuntu 20.04,
Is it because the ROS version is too low? But it's still ros2, why does the function change so much?

**Comment by JafarAbdi** [comment]
> > 代码在 CI 中编译没有问题：[https://github.com/moveit/py_binding_tools/actions/runs/10613882842`SingleThreadedExecutor`由此](https://github.com/moveit/py_binding_tools/actions/runs/10613882842%60SingleThreadedExecutor%60%E7%94%B1%E6%AD%A4) 得出`Executor,`​[提供`spin_all`](https://docs.ros.org/en/rolling/p/rclcpp/generated/classrclcpp_1_1Executor.html#_CPPv4N6rclcpp8Executor8spin_allENSt6chrono11nanosecondsE)。 为了帮助解决您的具体问题，如果您提供一些有关您的设置的信息会很有帮助： 您使用哪个 ROS 发行版？
> 
> ros2 foxy, ubuntu 20.04, Is it because the ROS version is too low? But it's still ros2, why does the function change so much?

Foxy is a no longer supported ROS 2 distribution (End of life was more than a 1 year ago), please see https://docs.ros.org/en/rolling/Releases.html for the supported ones!

**Comment by goodmanchd** [comment]
thanks for your time
